<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task25/blob/main/task25_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart.csv


In [ ]:
df=pd.read_csv("/content/heart.csv")

In [ ]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0


In [ ]:
X=df.drop('HeartDisease',axis=1)
y=df['HeartDisease']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

neighbors = [3, 5, 7, 9, 11, 13, 15]

best_acc = 0
best_k = 0

for k in neighbors:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"K = {k} --> Accuracy = {acc:.4f}")

    if acc > best_acc:
        best_acc = acc
        best_k = k

print("\nBest K =", best_k)
print("Best Accuracy =", best_acc)

K = 3 --> Accuracy = 0.8449
K = 5 --> Accuracy = 0.8581
K = 7 --> Accuracy = 0.8812
K = 9 --> Accuracy = 0.8845
K = 11 --> Accuracy = 0.9010
K = 13 --> Accuracy = 0.8845
K = 15 --> Accuracy = 0.8878

Best K = 11
Best Accuracy = 0.900990099009901


In [22]:
from sklearn.svm import SVC

C_values = [0.1, 1, 10, 100]

best_acc = 0
best_c = 0

for c in C_values:
    svm = SVC(C=c, kernel='rbf', random_state=42)
    svm.fit(X_train, y_train)

    y_pred = svm.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"C = {c} --> Accuracy = {acc:.4f}")

    if acc > best_acc:
        best_acc = acc
        best_c = c

print("\nBest C =", best_c)
print("Best Accuracy =", best_acc)

C = 0.1 --> Accuracy = 0.8614
C = 1 --> Accuracy = 0.8779
C = 10 --> Accuracy = 0.8350
C = 100 --> Accuracy = 0.8119

Best C = 1
Best Accuracy = 0.8778877887788779


In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

knn = KNeighborsClassifier()

grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=knn_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_knn.fit(X_train, y_train)

print("Best Parameters:", grid_knn.best_params_)
print("Best Cross Validation Accuracy:", grid_knn.best_score_)

test_acc = grid_knn.score(X_test, y_test)
print("Test Accuracy:", test_acc)

Best Parameters: {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'}
Best Cross Validation Accuracy: 0.8715447154471544
Test Accuracy: 0.8844884488448845


In [24]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm_params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

svm = SVC(random_state=42)

grid_svm = GridSearchCV(
    estimator=svm,
    param_grid=svm_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_svm.fit(X_train, y_train)

print("Best Parameters:", grid_svm.best_params_)
print("Best Cross Validation Accuracy:", grid_svm.best_score_)

test_acc = grid_svm.score(X_test, y_test)
print("Test Accuracy:", test_acc)

Best Parameters: {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}
Best Cross Validation Accuracy: 0.865040650406504
Test Accuracy: 0.8778877887788779


In [25]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier

knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

knn = KNeighborsClassifier()

random_knn = RandomizedSearchCV(
    estimator=knn,
    param_distributions=knn_params,
    n_iter=10,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

random_knn.fit(X_train, y_train)

print("Best Parameters:", random_knn.best_params_)
print("Best Cross Validation Accuracy:", random_knn.best_score_)

test_acc = random_knn.score(X_test, y_test)
print("Test Accuracy:", test_acc)

Best Parameters: {'weights': 'distance', 'n_neighbors': 9, 'metric': 'manhattan'}
Best Cross Validation Accuracy: 0.8682926829268294
Test Accuracy: 0.8910891089108911


In [26]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

svm_params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

svm = SVC(random_state=42)

random_svm = RandomizedSearchCV(
    estimator=svm,
    param_distributions=svm_params,
    n_iter=8,
    cv=5,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1
)

random_svm.fit(X_train, y_train)

print("Best Parameters:", random_svm.best_params_)
print("Best Cross Validation Accuracy:", random_svm.best_score_)

test_acc = random_svm.score(X_test, y_test)
print("Test Accuracy:", test_acc)

Best Parameters: {'kernel': 'rbf', 'gamma': 'scale', 'C': 1}
Best Cross Validation Accuracy: 0.865040650406504
Test Accuracy: 0.8778877887788779


In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("----- Random Forest -----")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

----- Random Forest -----
Accuracy: 0.8613861386138614
Confusion Matrix:
 [[108  15]
 [ 27 153]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.88      0.84       123
           1       0.91      0.85      0.88       180

    accuracy                           0.86       303
   macro avg       0.86      0.86      0.86       303
weighted avg       0.87      0.86      0.86       303



In [28]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ada = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada.fit(X_train, y_train)

y_pred_ada = ada.predict(X_test)

print("----- AdaBoost -----")
print("Accuracy:", accuracy_score(y_test, y_pred_ada))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ada))
print("Classification Report:\n", classification_report(y_test, y_pred_ada))

----- AdaBoost -----
Accuracy: 0.8646864686468647
Confusion Matrix:
 [[108  15]
 [ 26 154]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.88      0.84       123
           1       0.91      0.86      0.88       180

    accuracy                           0.86       303
   macro avg       0.86      0.87      0.86       303
weighted avg       0.87      0.86      0.87       303



In [29]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print("----- Gradient Boosting -----")
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gb))
print("Classification Report:\n", classification_report(y_test, y_pred_gb))

----- Gradient Boosting -----
Accuracy: 0.8679867986798679
Confusion Matrix:
 [[110  13]
 [ 27 153]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.89      0.85       123
           1       0.92      0.85      0.88       180

    accuracy                           0.87       303
   macro avg       0.86      0.87      0.87       303
weighted avg       0.87      0.87      0.87       303



In [30]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

xgb = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("----- XGBoost -----")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))

----- XGBoost -----
Accuracy: 0.8514851485148515
Confusion Matrix:
 [[107  16]
 [ 29 151]]
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.87      0.83       123
           1       0.90      0.84      0.87       180

    accuracy                           0.85       303
   macro avg       0.85      0.85      0.85       303
weighted avg       0.86      0.85      0.85       303



In [31]:
import pandas as pd
from sklearn.metrics import accuracy_score

comparison = pd.DataFrame({
    "Model": [
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_ada),
        accuracy_score(y_test, y_pred_gb),
        accuracy_score(y_test, y_pred_xgb)
    ]
})

print(comparison)

               Model  Accuracy
0      Random Forest  0.861386
1           AdaBoost  0.864686
2  Gradient Boosting  0.867987
3            XGBoost  0.851485


In [32]:
import joblib
joblib.dump(rf, "best_model.pkl")
print("Best model saved successfully!")

Best model saved successfully!


In [33]:
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [35]:
!pip install streamlit pyngrok

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 62.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 84.9 MB/s eta 0:00:00


In [36]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib

# Load files
model = joblib.load("best_model.pkl")
scaler = joblib.load("scaler.pkl")
columns = joblib.load("columns.pkl")

st.title("Heart Disease Prediction")

# User Inputs
age = st.number_input("Age", 18, 100, 40)

sex = st.selectbox("Sex", ["M", "F"])

chest = st.selectbox(
    "Chest Pain Type",
    ["ATA", "NAP", "ASY", "TA"]
)

bp = st.number_input("Resting BP", 50, 250, 120)

chol = st.number_input("Cholesterol", 0, 700, 200)

fast = st.selectbox("Fasting BS", [0,1])

ecg = st.selectbox(
    "Resting ECG",
    ["Normal","ST","LVH"]
)

hr = st.number_input("Max Heart Rate",60,220,150)

angina = st.selectbox(
    "Exercise Angina",
    ["Y","N"]
)

oldpeak = st.number_input(
    "Old Peak",
    value=1.0,
    step=0.1
)

slope = st.selectbox(
    "ST Slope",
    ["Up","Flat","Down"]
)

if st.button("Predict"):

    data = pd.DataFrame({
        "Age":[age],
        "Sex":[sex],
        "ChestPainType":[chest],
        "RestingBP":[bp],
        "Cholesterol":[chol],
        "FastingBS":[fast],
        "RestingECG":[ecg],
        "MaxHR":[hr],
        "ExerciseAngina":[angina],
        "Oldpeak":[oldpeak],
        "ST_Slope":[slope]
    })

    # Encoding
    data = pd.get_dummies(data, drop_first=True)

    # Match training columns
    data = data.reindex(columns=columns, fill_value=0)

    # Scale
    data = scaler.transform(data)

    # Prediction
    pred = model.predict(data)

    if pred[0] == 1:
        st.error("Heart Disease Detected")
    else:
        st.success("No Heart Disease")

Writing app.py


In [39]:
!pip install pyngrok

In [41]:
from pyngrok import ngrok

ngrok.set_auth_token("3HEmkd6vQyadnmiO0VVUPveicP2_2cAPTfgFK4YK6CRkKPYAi")

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://matrimony-stoppable-gainfully.ngrok-free.dev" -> "http://localhost:8501"


In [ ]:
!streamlit run app.py &



2026-07-30 20:05:16.192 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.75.253.194:8501

